"""empty message

Revision ID: 119422ff3e6b
Revises: 
Create Date: 2021-03-17 10:49:01.875905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119422ff3e6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('number_of_bedrooms', sa.String(length=80), nullable=True),
    sa.Column('number_of_bathrooms', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('price', sa.String(length=80), nullable=True),
    sa.Column('types', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_property')
    # ### end Alembic commands ###
